CREATE TABLE IF NOT EXISTS tb_user
(
    id                  bigint generated by default as identity,
    creation_date       timestamp,
    update_date         timestamp,
    uuid                varchar(255),
    username            varchar(255),
    password            varchar(255),
    email               varchar(255),
    person_id           bigint,
    role                varchar(255),
    primary key (id)
    );

CREATE TABLE IF NOT EXISTS tb_person
(
    id                  bigint generated by default as identity,
    creation_date       timestamp,
    update_date         timestamp,
    uuid                varchar(255),
    name                varchar(255),
    birthday            varchar(255),
    phone               varchar(255),
    user_id             bigint,
    primary key (id)
    );

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_86cal5mg9j0t8j9yn28n9iulc'
    ) THEN
ALTER TABLE tb_person ADD CONSTRAINT uk_86cal5mg9j0t8j9yn28n9iulc UNIQUE (uuid);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_86cal5mg9j0t8j9yn28n9ijjj'
    ) THEN
ALTER TABLE tb_user ADD CONSTRAINT uk_86cal5mg9j0t8j9yn28n9ijjj UNIQUE (uuid);
END IF;
END $$;

ALTER TABLE IF EXISTS tb_user
    ADD CONSTRAINT IF NOT EXISTS FK349pmtlc4ukgn1so04k2ls4jj foreign key (person_id) references tb_person;
