create table if not exists tb_filmes
(
    id                bigint generated by default as identity,
    data_atualizacao  timestamp,
    data_criacao      timestamp,
    adult             boolean,
    backdrop_path     varchar(255),
    genre_ids         varchar(255),
    original_language varchar(255),
    original_title    varchar(255),
    overview          varchar(255),
    popularity        bigint,
    poster_path       varchar(255),
    release_date      varchar(255),
    title             varchar(255),
    video             boolean,
    vote_average      bigint,
    vote_count        bigint,
    external_id       varchar,
    external_source   varchar,
    primary key (id)
);
