CREATE TABLE IF NOT EXISTS tb_user
(
    id                  bigint generated by default as identity,
    creation_date       timestamp,
    update_date         timestamp,
    uuid                varchar(255),
    username            varchar(255),
    password            varchar(255),
    email               varchar(255),
    person_id           bigint,
    role                varchar(255),
    primary key (id)
);

CREATE TABLE IF NOT EXISTS tb_person
(
    id                  bigint generated by default as identity,
    creation_date       timestamp,
    update_date         timestamp,
    uuid                varchar(255),
    name                varchar(255),
    birthday            varchar(255),
    phone               varchar(255),
    user_id             bigint,
    primary key (id)
);

DO $$
BEGIN
BEGIN
ALTER TABLE tb_person ADD CONSTRAINT UK_86cal5mg9j0t8j9yn28n9iulc UNIQUE (uuid);
EXCEPTION
        WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint UK_86cal5mg9j0t8j9yn28n9iulc already exists.';
END;
END $$;

DO $$
BEGIN
BEGIN
ALTER TABLE tb_user ADD CONSTRAINT UK_86cal5mg9j0t8j9yn28n9ijjj UNIQUE (uuid);
EXCEPTION
        WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint UK_86cal5mg9j0t8j9yn28n9ijjj already exists.';
END;
END $$;

ALTER TABLE IF EXISTS tb_user ADD CONSTRAINT IF NOT EXISTS FK349pmtlc4ukgn1so04k2ls4jj FOREIGN KEY (person_id) REFERENCES tb_person(id);
