CREATE TABLE IF NOT EXISTS tb_user
(
    id                  bigint generated by default as identity,
    creation_date       timestamp,
    update_date         timestamp,
    uuid                varchar(255),
    username            varchar(255),
    password            varchar(255),
    email               varchar(255),
    person_id           bigint,
    role                varchar(255),
    primary key (id)
);

CREATE TABLE IF NOT EXISTS tb_person
(
    id                  bigint generated by default as identity,
    creation_date       timestamp,
    update_date         timestamp,
    uuid                varchar(255),
    name                varchar(255),
    birthday            varchar(255),
    phone               varchar(255),
    user_id             bigint,
    primary key (id)
);

ALTER TABLE IF EXISTS tb_person
    ADD CONSTRAINT IF NOT EXISTS UK_86cal5mg9j0t8j9yn28n9iulc unique (uuid);
ALTER TABLE IF EXISTS tb_user
    ADD CONSTRAINT IF NOT EXISTS UK_86cal5mg9j0t8j9yn28n9ijjj unique (uuid);
ALTER TABLE IF EXISTS tb_user
    ADD CONSTRAINT IF NOT EXISTS FK349pmtlc4ukgn1so04k2ls4jj foreign key (person_id) references tb_person;
