create table tb_property_demand
(
    id                              bigint generated by default as identity,
    creation_date                   timestamp,
    update_date                     timestamp,
    uuid                            varchar(255),
    contract_type                   varchar(255),
    property_type                    varchar(255),
    bedrooms_number                 varchar(255),
    furnished                       boolean default false,
    pet_friendly                    boolean default false,
    suggested_value_for_rent        varchar(255),
    suggested_value_for_sale        varchar(255),
    suggested_value_for_seasonal    varchar(255),
    demand_id                       bigint,
    address_id                      bigint,
    user_id                         bigint,
    deleted                         boolean default false,
    primary key (id)
);

create table tb_demand
(
    id                      bigint generated by default as identity,
    creation_date           timestamp,
    update_date             timestamp,
    uuid                    varchar(255),
    property_demand_id      bigint,
    user_id                 bigint,
    annotation              varchar(255),
    contact                 varchar(255),
    is_deleted              boolean default false,
    primary key (id)
);

alter table tb_demand
    add constraint UK_86cal5mg9j0t8j9yn28n9iurt unique (uuid);
alter table tb_demand
    add constraint FK349pmtlc4ukgn1so04k2ls444 foreign key (property_demand_id) references tb_property_demand;

alter table tb_property_demand
    add constraint UK_86cal5mg9j0t8j9yn28n9iuss unique (uuid);
alter table tb_property_demand
    add constraint FK349pmtlc4ukgn1so04k2ls4kk foreign key (demand_id) references tb_demand;
alter table tb_property_demand
    add constraint FK349pmtlc4ukgn1so04k2ls4kl foreign key (address_id) references tb_address;
alter table tb_property_demand
    add constraint FK349pmtlc4ukgn1so04k2ls4pp foreign key (user_id) references tb_user;
