create table if not exists tb_pessoas
(
    id               bigint generated by default as identity,
    data_atualizacao timestamp,
    data_criacao     timestamp,
    uuid             varchar(255),
    nome             varchar(255),
    data_nascimento  timestamp,
    usuario_id       bigint,
    primary key (id)
);

alter table if exists tb_pessoas
    add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (usuario_id) references tb_usuarios;
