create table if not exists tb_offer
(
    id                      bigint generated by default as identity,
    creation_date           timestamp,
    update_date             timestamp,
    uuid                    varchar(255),
    demand_id               bigint,
    text                    varchar(2000),
    user_id                 bigint,
    user_email              varchar(255),
    username_user           varchar(255),
    user_contact            varchar(255),
    accepted                boolean default false,
    deleted                 boolean default false,
    primary key (id)
);

alter table tb_offer
    add constraint if not exists UK_86cal5mg9j0t8j9yn28n9ityu unique (uuid);
alter table tb_offer
    add constraint if not exists FK349pmtlc4ukgn1so04k2ls4ty foreign key (demand_id) references tb_demand;
alter table tb_offer
    add constraint if not exists FK349pmtlc4ukgn1so04k2ls4yt foreign key (user_id) references tb_user;
