create table tb_offer
(
    id                      bigint generated by default as identity,
    creation_date           timestamp,
    update_date             timestamp,
    uuid                    varchar(255),
    demand_id               bigint,
    text                    varchar(255),
    user_id                 bigint,
    primary key (id)
);

alter table tb_offer
    add constraint UK_86cal5mg9j0t8j9yn28n9iurt unique (uuid);
alter table tb_offer
    add constraint FK349pmtlc4ukgn1so04k2ls4ty foreign key (demand_id) references tb_demand;
alter table tb_offer
    add constraint FK349pmtlc4ukgn1so04k2ls4yt foreign key (user_id) references tb_user;
