create table tb_payment
(
    id                     bigint generated by default as identity,
    creation_date          timestamp,
    update_date            timestamp,
    uuid                   varchar(255),
    user_id                bigint,
    plan                   varchar(255),
    event_id               varchar(255),
    object_id              varchar(255),
    user_name              varchar(255),
    client_reference       bigint,
    amount_total           double precision,
    authorization_date     timestamp,
    expiration_date        timestamp,
    primary key (id)
);
